# @format

name: Deploy to Google Apps Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run validation (lint + tests)
        run: npm run validate

      - name: Check test coverage
        run: npm run test:coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript to Code.gs
        run: npm run build

      - name: Setup clasp credentials
        run: |
          echo '${{ secrets.CLASP_CREDENTIALS }}' > ~/.clasprc.json

      - name: Install clasp globally
        run: npm install -g @google/clasp

      - name: Verify clasp login status
        run: clasp status

      - name: Push to Google Apps Script
        run: clasp push --force

      - name: Deploy web app
        run: clasp deploy --description "Deployed from GitHub Actions $(date)"
        continue-on-error: true

      - name: Get deployment info
        run: clasp deployments
        continue-on-error: true
