name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run linting
      run: npm run lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup clasp credentials
      run: |
        mkdir -p ~/.config/@google
        echo '${{ secrets.CLASP_CREDENTIALS }}' > ~/.clasprc.json
        echo '${{ secrets.CLASP_CONFIG }}' > .clasp.json
    
    - name: Install clasp globally
      run: npm install -g @google/clasp
    
    - name: Push to Google Apps Script
      run: clasp push --force
    
    - name: Deploy web app
      run: clasp deploy --description "Deployed from GitHub Actions $(date)"
      continue-on-error: true
    
    - name: Get deployment info
      run: clasp deployments
      continue-on-error: true